BoldGrid/post-and-page-builder

- includes/class-boldgrid-editor-crop.php
- includes/class-boldgrid-editor.php
- readme.txt
> Image Cropping hanges #55

- readme.txt
1. [ ] Review the readme at [wpreadme.com](https://wpreadme.com/)
> Updating readme to include support info in the faq

- includes/class-boldgrid-editor-premium.php
- includes/class-boldgrid-editor.php
Ticket handles the same issue just fixed within the Backup Plugin - https://github.com/BoldGrid/boldgrid-backup/pull/117
> Move admin notices

- includes/class-boldgrid-editor-config.php
I was not able to get the notice, but this should fix it.
> Fix php 7.4 deprecated notice. Fixes #142

- includes/class-boldgrid-editor-assets.php
@rramo012 I'm not sure how you want to go about addressing #140, but I took a stab at it. Let me know what you think.
> Temporary fix for WP 5.5 wpColorPickerL10n issue. Fixes #140

- composer.json
- composer.lock
> resolves #192

- includes/class-boldgrid-editor-setting.php
> resolves #198

- includes/builder/class-boldgrid-editor-builder.php
> Add primary and secondary button fallbacks

- assets/scss/builder/_tinymce.scss
> fix paragraph dropdown in full screen

- assets/js/builder/css/draggable.css
- assets/js/editor.js
- package.json
- yarn.lock
> update fourpan package

- assets/js/builder/controls/container.js
- assets/js/builder/tinymce/wp-mce-draggable.js
> resolves issue 254

- includes/Widget/Menu.php
[resolves #66](https://github.com/BoldGrid/crio-premium/issues/66)
> add menu direction control

- includes/class-boldgrid-editor-theme.php
Helps to resolve https://github.com/BoldGrid/boldgrid-theme-framework/issues/547
> Adds background styles to editor

- includes/Widget/Menu.php
- includes/class-boldgrid-editor-theme.php
> Add menu direction controls

- assets/js/builder/component/widget/instance.js
- includes/class-boldgrid-editor-theme.php
resolves boldgrid/boldgrid-theme-framework#559
> Bgtfw issue 559

- includes/class-boldgrid-editor-theme.php
- package.json
- post-and-page-builder.php
- readme.txt
> resolves get_background_classes null return

- README.md
- includes/builder/class-boldgrid-editor-builder.php
- includes/class-boldgrid-editor-assets.php
- includes/template/button.php
> Add third-party theme buttons

- assets/js/editor/editor.js
- includes/View/Feature/MoreCentral.php
- includes/View/Plugins.php
- includes/class-boldgrid-editor-premium.php
- includes/config/config.plugin.php
* add ppb-button class to 'reset_anchor_spaces'
* add filtering of premium URLs
> Issue 397 (#404)

- includes/class-boldgrid-editor-setting.php
> fix saved editor for CPTs

- includes/class-boldgrid-editor-assets.php
Resolves #444, Resolves, #443, Resolves #446.
NOTE: Testing instructions are for issue #444 . Issues #443 and #446 require special configurations, and were tested separately.
1. Install This branch of PPB.
[post-and-page-builder.zip](https://github.com/BoldGrid/post-and-page-builder/files/9602331/post-and-page-builder.zip)
[one-click-install](https://www.boldgrid.com/central/cloud-wordpress/try?themes=crio&plugins=https://github.com/BoldGrid/post-and-page-builder/files/9602331/post-and-page-builder.zip)
2. Install Crio
3. Install Gravity Forms
4. Create a MultiPage Form. ( [See Instructions here](https://docs.gravityforms.com/creating-multi-page-forms/) )
5. Add the form to a page using the 'Add Form' PPB component. 
6. View the page, and ensure that the Form works as expected, without JS …
> resolve #444

- assets/js/builder/controls/element/background.js
- assets/js/builder/controls/element/tables.js
- assets/js/builder/gridblock/filter.js
- assets/js/public.js
- assets/js/tinymce_tables.js
- bin/package.sh
- includes/class-boldgrid-editor-assets.php
- includes/media/class-boldgrid-editor-layout.php
- package.json
- post-and-page-builder.php
- readme.txt
- yarn.lock
Resolves #403
Resolves #438
Resolves #448
Resolves #445 
Resolves #444
Resolves #443
Resolves #446
The Testing instructions for each issue resolved in 1.21.2 can be found in each issues respective Pull Request, which can be found in the list below. If the PR instructs you to install a specific test zip, [install the 1.21.2-rc1 zip file instead](https://downloads.wordpress.org/plugin/post-and-page-builder.1.21.2-rc1.zip). 
Issue #403 -> [PR#452](https://github.com/BoldGrid/post-and-page-builder/pull/452)
Issue #448 -> [PR#453](https://github.com/BoldGrid/post-and-page-builder/pull/453)
Issue #438 -> [PR#456](https://github.com/BoldGrid/post-and-page-builder/pull/456)
This issue requires the ability to modify your `wp-config.php` file.
Issue #445 -> …
> Branch 1.21.2

- assets/js/builder/controls/element/background.js
- assets/scss/builder/panel/_background.scss
Resolves #426 
1. Install test zip.
[post-and-page-builder.zip](https://github.com/BoldGrid/post-and-page-builder/files/9803550/post-and-page-builder.zip)
2. Set a background to a preset gradient.
3. Click on the 'Settings' button in the preview panel of the Background Panel
4. Ensure that the two gradient color controls are shown, as well as the gradient direction control.
> add back gradient controls

- assets/js/builder/controls/element/background.js
> gradients change with palette changes

- package.json
- yarn.lock
> Updates boldgrid/components dependancy

- assets/json/builder.json
- package.json
- post-and-page-builder.php
- readme.txt
- yarn.lock
ISSUES:
* Fixes #401 -> PR #523
* Fixes #459, #512 -> PR #524
PROJECT: [PPB 1.23.1](https://github.com/orgs/BoldGrid/projects/14/views/11)
{LINK TO TEST ZIP FILES HERE}
2.
> Branch 1.23.1

- components/class-boldgrid-components-shortcode.php
- composer.json
- composer.lock
- controls/class-boldgrid-controls-page-title.php
- includes/class-boldgrid-editor-assets.php
- includes/class-boldgrid-editor-fs.php
- includes/class-boldgrid-editor-mce.php
- includes/class-boldgrid-editor-theme.php
- includes/gridblock/class-boldgrid-editor-gridblock-post.php
- package.json
- post-and-page-builder.php
- readme.txt
This resolves a lot of PHP8.2 deprecated notices.
> Php8.2 fixes

- includes/template/image-filter.php
> Fix no lower p in WordPress

- assets/js/builder/component/icon/control.js
- assets/scss/builder/panel/_background.scss
- assets/scss/builder/panel/_icon.scss
- includes/template/icon.php
- package.json
- post-and-page-builder.php
- readme.txt
ISSUE: Resolves #558 and Resolves #105
[post-and-page-builder-1.26.1-rc.1.zip](https://github.com/BoldGrid/post-and-page-builder/files/13941880/post-and-page-builder-1.26.1-rc.1.zip)
2. Install Crio as your active theme.
3. Open a page or post in PPB.
4. Add an Icon to the page, and ensure that the search input shows at the top of the icon control panel, and responds appropriately to input.
5. Ensure that the icons shown match or include the search string.
6. Open the background image control, and ensure that the Add Image icon styling is correct.
> 1.26.1 Patch

- assets/js/builder/premium/component.js
ISSUE: Resolves #532 
PROJECT: [PPB Issues > Current Release Cycle](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder-1.26.2-issue-532.zip](https://github.com/BoldGrid/post-and-page-builder/files/14051174/post-and-page-builder-1.26.2-issue-532.zip)
2. If PPB Premium is installed and active, deactivate it. 
3. Ensure you are using a free connect key.
4. Edit a page or post.
5. Click the '+' icon to add a block component.
6. Ensure that the 'Tabs' upsell button has the first letter capitalized like it should.
7. Ensure that clicking the button takes you to a cart page, rather than an upsell page.
> Enhancement - tabs upsell

- yarn.lock
ISSUE: Resolves #512 
PROJECT: [PPB Issues](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder-1.26.2-issue-512.zip](https://github.com/BoldGrid/post-and-page-builder/files/14197009/post-and-page-builder-1.26.2-issue-512.zip)
2. Edit a page or post.
3. Select an element that does NOT have a border.
4. Open the 'Advanced Controls' panel.
5. Navigate to the 'Border' Control
6. Change the border style from 'None' to any of the other options, such as 'Solid'. When you do so, the border width controls will be shown, with the initial border-width being 0. Ensure that this is accurately reflected on the selected element. IE `border-style: solid; border-width: 0`
> Border visual bug in admin

- includes/gridblock/class-boldgrid-editor-gridblock-post.php
ISSUE: Resolves #605 
[post-and-page-builder-1.26.6-issue-605.zip](https://github.com/user-attachments/files/16088332/post-and-page-builder-1.26.6-issue-605.zip)
2. Install WP 6.6-RC.2
3. Install Crio
4. Click on `Appearance > Patterns` in the WP Admin menu.
5. Ensure that you are taken to the PPB Block Library ( `edit.php?post_type=bg_block` )
> fix Appearance > Patterns link

- README.md
- includes/class-boldgrid-editor-ajax.php
- package.json
- post-and-page-builder.php
- readme.txt
ISSUE: Resolves #612 
{LINK TO TEST ZIP FILES HERE}
Example request:
```
Payload:
Request Raw:
POST /wp-admin/admin-ajax.php HTTP/1.1
Host: YOUR_HOST
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://wpcraft.com:1337/wp-admin/edit.php?post_type=bg_block
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: YOUR_COOKIES
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 602
action=boldgrid_canvas_image&boldgrid_gridblock_image_ajax_nonce=YOUR_NONCE&image_data=data:image/3gp2;base64,PD94bWwgdmV …
```
> Patch Vulnerability reported by WordFence

- .travis.yml
- assets/js/builder/component/button/control.js
- assets/js/builder/controls/element/background.js
- assets/js/builder/controls/element/tables.js
- assets/js/builder/notice/onb-videos/notice.js
- includes/class-boldgrid-editor-assets.php
- includes/template/tables.php
- package.json
- post-and-page-builder.php
- readme.txt
ISSUES:
Resolves #601 
Resolves #607 
Resolves #603 
Resolves #619 
https://github.com/BoldGrid/post-and-page-builder/releases/download/1.27.1-rc.1/post-and-page-builder.zip
See Testing instructions from the following PRs:
New Background Control should not be able to save a null value as a color. [#617](https://github.com/BoldGrid/post-and-page-builder/pull/617)
Cannot create a button with the neutral background color [#616](https://github.com/BoldGrid/post-and-page-builder/pull/616)
Advanced Controls panel show on Tutorial Videos when they should not [#615](https://github.com/BoldGrid/post-and-page-builder/pull/615)
> Branch 1.27.1

- assets/js/builder/css/draggable.css
ISSUE: Resolves #622 
[post-and-page-builder-1.27.2-issue-622.zip](https://github.com/user-attachments/files/17135316/post-and-page-builder-1.27.2-issue-622.zip)
2. Open a page or post with a full-width section.
3. Ensure that the row and content popovers, which show on the sides, are fully visible
> add extra padding to iframe

- assets/js/builder/css/draggable.css
- assets/js/public.js
- package.json
- post-and-page-builder.php
- readme.txt
> Branch 1.27.2

- README.md
- includes/class-boldgrid-editor-preview.php
- package.json
- post-and-page-builder.php
- readme.txt
> security vulnerability fix

- includes/class-boldgrid-editor.php
- package.json
- post-and-page-builder.php
- readme.txt
Fix _load_textdomain_just_in_time notices
[post-and-page-builder-1.27.8.zip](https://github.com/user-attachments/files/19453811/post-and-page-builder-1.27.8.zip)
> Resolves #640
