includes/class-boldgrid-editor-theme.php
updates method to check for boldgrid theme name to stop using textdomains.  This will allow people making child themes to support the editor not have to include their theme name as "BoldGrid Somename" with a textdomain `boldgrid-somename`
=> check for theme name by Author and child theme by parent.  fixes #79

includes/class-boldgrid-editor-theme.php
Error
`{type: "notice", message: "Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH'", file: "wp-includes/theme.php", line: 152,
stack: Array(6), …}
component: "Plugin: post-and-page-builder"
file: "wp-includes/theme.php"
line: 152
message: "Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH'"
stack: Array(6)
0: "is_child_theme()"
1: "Boldgrid_Editor_Theme::get_boldgrid_theme_name()"
2: "Boldgrid_Editor_Theme::is_editing_boldgrid_theme()"
3: "Boldgrid_Editor->__construct()"
4: "boldgrid_editor_setup()"
5: "do_action('setup_theme')"`
WP Code:
https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/theme.php#L151 
Constants defined here: 
https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-settings.php#L446 a couple lines after setup theme
=> Fixing undefined constant error

assets/js/builder/controls/element/background.js, assets/js/public.js
resolves #448 
1. Install the test zip attached or use the [one-click-install link](https://www.boldgrid.com/central/cloud-wordpress/try?plugins=https://github.com/BoldGrid/post-and-page-builder/files/9576806/post-and-page-builder-1.21.2.zip).
[post-and-page-builder-1.21.2.zip](https://github.com/BoldGrid/post-and-page-builder/files/9576806/post-and-page-builder-1.21.2.zip)
2. Create a post where one or more columns have a standard background image and a different hover image.
3. Set the hover image to 'Show hover background on mobile'
4. Add a child element to the column, and set the hover effects to 'Show on Hover'
5. Save the post, and view it on a mobile device ( phone or tablet )
6. Ensure that the hover image is shown for the column, and not the standard image on a mobile device.
7. …
=> fix mobile hover boxes

yarn.lock
Resolves #415 
1. Install Post and Page Builder using the following link: 
[post-and-page-builder.zip](https://github.com/BoldGrid/post-and-page-builder/files/9759087/post-and-page-builder.zip)
2. Create or Edit a post with text.
3. Edit the text properties for a text component.
4. ensure that the 'Line Height' slider is capable of going from 1-100px.
=> update boldgrid/controls for line-height fix

yarn.lock
ISSUE: Resolves #459 
Resolves #512 
NOTE: Both issues were caused by the same root issue, that the style `border-width:0px` was being added to new elements unnecessarily. Therefore, both issues are being resolved in the same PR. This issue was being caused by the @boldgrid/controls repository. See [commit #1f299be](https://github.com/BoldGrid/controls/commit/1f299be41f23eec4aaebeefd1cef4b27892ba62a)
PROJECT: [PPB 1.23.1](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder.zip](https://github.com/BoldGrid/post-and-page-builder/files/11192282/post-and-page-builder.zip)
2. Add a new component. Specifically ensure you test with Buttons, as these were one specifically reported issue.
3. Ensure that the new component does …
=> Issues 459 & 512 - Fix border issues with newly added components

README.md, assets/js/forms/default-editor/form.js, includes/View/Settings.php, includes/class-boldgrid-editor-assets.php, package.json, post-and-page-builder.php, readme.txt
ISSUE: Resolves #540 
This vulnerability was reported based on the `submitDefaultEditor` method not using nonce validation. However, this method is actually called by the `formActionRoute` , therefore the nonce validation is being added there.
=> add nonce validation

package.json, post-and-page-builder.php, yarn.lock
ISSUE: Resolves #520 
[post-and-page-builder-1.25.1-issue520.zip](https://github.com/BoldGrid/post-and-page-builder/files/12937470/post-and-page-builder-1.25.1-issue520.zip)
2. Create a table using PPB table designer, and ensure the 'Responsive Tables' option is checked for phones.
3. Save the page or post with the table you've created.
4. Visit the page or post using an iPhone, or using BrowserStack.
5. Ensure that the tables resize accordingly for the device.
=> resolves Tables are very wide on iOS mobile devices (12, chrome) #520

includes/builder/class-boldgrid-editor-builder.php, yarn.lock
ISSUE: Resolves #538 
[post-and-page-builder-1.25.1-issue538.zip](https://github.com/BoldGrid/post-and-page-builder/files/12886642/post-and-page-builder-1.25.1-issue538.zip)
2. Set an animation to an element.
3. Save and reload the page / post with the animation.
4. Open the animation control, and ensure that the selected animation is shown in the control.
5. Select the 'None' option for the animation control, and ensure that the animation is removed from the element.
6. Save and reload, and ensure it is still set to 'None'
=> Editor is not detecting animations on content - Issue 538

yarn.lock
ISSUE: Resolves #535 
[post-and-page-builder-1.25.1-issue-535.zip](https://github.com/BoldGrid/post-and-page-builder/files/12937924/post-and-page-builder-1.25.1-issue-535.zip)
2. Create a new page or post.
3. Add an element of your choice that does not have a box-shadow.
4. Click on the 'Advanced Controls' option for that element.
5. Once the panel opens, inspect the element and ensure that a box-shadow inline style hasn't been added to the element.
6. Add a box-shadow to the element, and ensure it is added correctly.
=> Opening Advanced Controls adds a box shadow to every element #535

assets/js/builder/controls/color.js
ISSUE: Resolves #527 
[post-and-page-builder-1.25.1-issue-527.zip](https://github.com/BoldGrid/post-and-page-builder/files/12938153/post-and-page-builder-1.25.1-issue-527.zip)
2. Change the font color of an element to the neutral theme color ( last color in the palette )
3. Change the font color of that same element to some other theme color ( 1, 2, 3, etc )
4. Inspect the element and ensure that the 'color-neutral-color' class was removed from the element and the color of the text accurately reflects the chosen palette color.
5. Repeat steps 2 - 4 but instead of font color, change the outline color, and the border color.
=> fix neutral colors not being removed from elements

assets/js/builder/controls/generic/table-borders.js
ISSUE: Resolves #546
[post-and-page-builder-1.25.1-issue-546.zip](https://github.com/BoldGrid/post-and-page-builder/files/12949690/post-and-page-builder-1.25.1-issue-546.zip)
2. Add a table to a page or post
3. Manually adjust the height of the rows in the table.
4. Set a border with a palette color to the rows on the table.
5. Save and refresh the page.
6. Ensure that the color changes save.
7. Repeat with columns and heading.
=> Tables - color palette borders do not stay on page save #546

includes/class-boldgrid-editor-crop.php
ISSUE: Resolves #476 
PROJECT: [PPB Issues > Current Release Cycle](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder-1.26.2-issue-476.zip](https://github.com/BoldGrid/post-and-page-builder/files/14043483/post-and-page-builder-1.26.2-issue-476.zip)
2. Install BoldGrid Inspirations.
3. Use a connect key that has some image coins on it, or contact @jamesros161 if you need to get coins added for this test.
4. Replace an image on a page with a non-free image from the Connect Search. Ensure that the image gets cropped during the process. The cropping is what caused the issue before. 
5. Save the page, then go to Transactions > Cart / Checkout
6. Purchase the image.
7. Return to the page, and ensure that the image you …
=> BG Connect Search - Purchased images not being replaced

assets/scss/builder/panel/_navigation.scss, yarn.lock
ISSUE: Resolves #533 
PROJECT: [PPB Issues > Current Release Cycle](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder-1.26.2-issue-533.zip](https://github.com/BoldGrid/post-and-page-builder/files/14067331/post-and-page-builder-1.26.2-issue-533.zip)
2. Open a panel with an advanced customize enabled ( ex: buttons or column shape ).
3. Click on the 'Customize' button on the bottom of the panel.
4. Navigate to the Padding, Margin, Border Radius and Border Width controls
5. Ensure that the PX unit isn't cut off, and appears as shown below:
=> PX option is cut off from some popovers

includes/class-boldgrid-editor-assets.php
ISSUE: Resolves #517 
PROJECT: [PPB Issues](https://github.com/orgs/BoldGrid/projects/14/views/11)
[post-and-page-builder-premium-1.1.4-issue-517.zip](https://github.com/BoldGrid/post-and-page-builder/files/14101657/post-and-page-builder-premium-1.1.4-issue-517.zip)
2. View a page that does NOT utilize the parallax background feature.
3. Use the Chrome Dev Tools to view the list of JS files loaded ( this can be done under the 'Network' tab of the dev tools )
4. Ensure that the file `jquery.stellar.js` is not loaded.
5. Edit the page to include a parallax background somewhere on the page.
6. Reload the page and ensure that the `jquery.stellar.js` file IS loaded and that the parallax effect works as expected.
=> Conditionally load steller.js

components/class-boldgrid-components-shortcode.php
ISSUE: Resolves #580 
PROJECT: [PPB Issues](https://github.com/orgs/BoldGrid/projects/14/views/11?pane=issue&itemId=56499157)
[post-and-page-builder-1.26.3-issue-580.zip](https://github.com/BoldGrid/post-and-page-builder/files/14619782/post-and-page-builder-1.26.3-issue-580.zip)
2. Create a non-admin user, such as a contributor.
3. Login as the contributor user
4. Create a post, and make sure that the 'Block' widget is not shown when trying to add a component
5. Make sure that the 'Block' widget shows when logged in as an admin.
=> don't show wp_block widget for non-admin users

assets/scss/builder/_tinymce.scss
ISSUE: Resolves #606 
[post-and-page-builder-1.26.6-issue-606.zip](https://github.com/user-attachments/files/16088458/post-and-page-builder-1.26.6-issue-606.zip)
2. Install WP 6.6-RC.2
3. Install Crio
4. Edit a page or post. 
5. Add a link using the in-editor link tool
6. Ensure that the text label 'Paste URL or type to search' appears above the input bar, rather than to the side of it.
7. Ensure that when editing a link, that the link is shown above the edit buttons, and not beside it.
Incorrect: 
Correct:
Incorrect:
Correct:
=> Fix link ui styling

assets/js/builder/controls/element/background.js, includes/class-boldgrid-editor-assets.php
ISSUE: Resolves #601
[post-and-page-builder-1.27.1-issue-601.zip](https://github.com/user-attachments/files/16997372/post-and-page-builder-1.27.1-issue-601.zip)
** Note: I do not know how to replicate the issue where the `null` value was being saved in the color array. Therefore, QA testing will primarily be about testing to ensure that saving colors still works properly **
2. Install Crio.
3. Go to a page or post.
4. Open the new Background Color control, and adjust save a few colors ( palette colors as well as regular colors ).
5. Save the post ( this triggers the actual saving in the database ).
6. Reload the page, and ensure all saved colors are still there.
=> add validation check for saved colors

assets/js/public.js
ISSUE: Resolves #624 
[post-and-page-builder-1.27.2-issue-624.zip](https://github.com/user-attachments/files/17296989/post-and-page-builder-1.27.2-issue-624.zip)
2. Install an inspiration with a section divider ( in the testing the DH Dog Care theme was used )
3. Add a sticky header in the customizer, but change the sticky header background to a color other than the color used by the section divider ( in this case the color set to color-2 )
4. Verify that the section divider keeps the correct color instead of taking the color of the sticky header.
=> Fix section divider colors on CPH & Sticky Header.

package.json, yarn.lock
ISSUE: Resolves #604 
[post-and-page-builder-1.27.4-issue-604.zip](https://github.com/user-attachments/files/18084665/post-and-page-builder-1.27.4-issue-604.zip)
2. Use Crio, open the Customizer and navigate to Design > Pages > Container and set to Full Width
3. Create a page and add a fixed width section (just container class, not container-fluid)
4. Add a table and toggle the setting for Responsive Table on tablet / phones. Ensure that the table is the only thing in the section.
5. Preview the page and drag the screen in so it's phone view narrow
6. Ensure that the table is taking up the full width of the container.
7. Test on an iOS device as well, as this issue was originally by a change made to fix tables being too wide on iOS devices.
=> Fix narrow tables on mobile.

assets/js/builder/component/button/control.js
ISSUE: Resolves #507 
[post-and-page-builder-1.27.4-issue-507.zip](https://github.com/user-attachments/files/18083028/post-and-page-builder-1.27.4-issue-507.zip)
2. Install Crio
3. Add content that uses the primary and / or secondary button classes from Crio. Starter Content works for this.
4. Edit the page / post in PPB.
5. Click on a button that has the primary / secondary class, and click on the "Button Design" button in the top menu.
6. Ensure that the 'Customize Button' isn't shown in the footer of the Button Design panel.
7. Change the button to one of the "Sample Designs" or "My Designs" buttons if any exist
8. Ensure that the 'Customize Button' is now shown in the footer.
=> don't show customize option for crio theme buttons
